### ISSUE TITLE
Documentation corrections required

### ISSUE THREAD

**Issue by davidackerman** [janelia-cellmap/dacapo#58]
This issue is for any documentation issues that come up during the hackathon. Here are some:

The following config files all have some duplicated documentation:
1. [MissingAnnotationsMaskConfig](https://github.com/janelia-cellmap/dacapo/blob/13ae1f0fa009f86758b30967323450b5ceecba5b/dacapo/experiments/datasplits/datasets/arrays/missing_annotations_mask_config.py#L11)
2. [BinarizeArrayConifg](https://github.com/janelia-cellmap/dacapo/blob/13ae1f0fa009f86758b30967323450b5ceecba5b/dacapo/experiments/datasplits/datasets/arrays/binarize_array_config.py#L10)
3. [IntensityArrayConfig](https://github.com/janelia-cellmap/dacapo/blob/13ae1f0fa009f86758b30967323450b5ceecba5b/dacapo/experiments/datasplits/datasets/arrays/intensity_array_config.py#L8)

**Comment by rhoadesScholar** [comment]
old version lives at:
funkelab.github.io/dacapo/overview.html

**Comment by davidackerman** [comment]
cellmap version: https://janelia-cellmap.github.io/dacapo/overview.html

**Comment by cmalinmayor** [comment]
I have been working on updating the API documentation, and generally the janelia-cellmap.github.io documentation website. I updated the theme to RTD for easier navigation, used autoapi to auto-generate the API documentation from the docstrings with auto-discovery, and included the README as the homepage. Still to do:
- [ ] Merge from dev/main to main and verify the github action works as expected with the new changes and the new docs get deployed.
- [ ] Add back in explanatory content. I moved the old rsts into a docs/temp folder, and it remains to go through it, add it back in where relevant, update or remove it where not.
- [ ] Relatedly, improve the README to represent the most important high level information. Then, since it is automatically included as the main page of the docs website, the most important info will be in both places automatically (docs website and github main page).
- [ ] Fix potential issues with formatting and auto-api discovery. There were many warnings when building it, which says that some of the ways we have organized the code or docs confused the autodiscovery.
- [ ] Improve docstring coverage and quality (including issues listed above if relevant)
- [ ] Limit the depth of the tree displayed when you click on API (currently it shows literally every file/class)
